language: ruby
branches:
  only:
    - master
rvm:
  - 2.5.9
  - 2.6.9
  - 2.7.5
env:
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=6.0.0"
  - "RAILS_VERSION=6.1.0"
  - "RAILS_VERSION=7.0.0"
jobs:
  exclude:
    - rvm: 2.7.5
      env: "RAILS_VERSION=6.0.0"
    - rvm: 2.7.5
      env: "RAILS_VERSION=5.2.0"
    - rvm: 2.7.5
      env: "RAILS_VERSION=5.0.0"
    - rvm: 2.5.9
      env: "RAILS_VERSION=7.0.0"
    - rvm: 2.6.9
      env: "RAILS_VERSION=7.0.0"
